services:
  python-dev:
    build: .
    container_name: pycharm-python-sandbox
    volumes:
      # Mount source code for live editing
      - .:/workspace
      # Preserve pip cache
      - pip-cache:/home/developer/.cache/pip
    working_dir: /workspace
    # Keep container running for development
    tty: true
    stdin_open: true
    command: sleep infinity  # Keep container running
    # Optional: expose ports if you'll run web services
    ports:
      - "8001:8000"
      - "5001:5000"
    environment:
      - PYTHONPATH=/workspace/src


volumes:
  pip-cache: